name: lab1_flutter
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  equatable: ^0.6.0
  flutter_slidable: ^0.5.4
  font_awesome_flutter: ^8.5.0
  provider: ^3.1.0
  sqflite: ^1.1.7+1
  path: ^1.6.4
  http: ^0.12.0+2
  connectivity: ^0.4.5+6
  flushbar: ^1.5.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  fonts:
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-Regular.ttf